# Generates docs/ue5_python_api_reference.md — a build-accurate reference of the
# methods available on the high-value `unreal` classes/subsystems for scripting
# via python/execute. Run it through the live editor (it must be running):
#   mcp tools/call python/execute_file {file_path: ".../generate_api_reference.py"}
# or paste into the Output Log Python console. Re-run after an engine/plugin
# upgrade to refresh. The list is curated; for ANY class use python/inspect_class
# or dir(unreal.<Class>) to get the live API.

import unreal
import os

# Curated high-value classes, grouped. Add to taste.
GROUPS = [
    ("Editor subsystems (unreal.get_editor_subsystem / get_engine_subsystem)", [
        "EditorActorSubsystem", "UnrealEditorSubsystem", "LevelEditorSubsystem",
        "EditorAssetSubsystem", "EditorUtilitySubsystem", "StaticMeshEditorSubsystem",
        "SkeletalMeshEditorSubsystem", "SubobjectDataSubsystem", "LayersSubsystem",
        "AssetEditorSubsystem", "EditorActorFolders",
    ]),
    ("Asset / content helper libraries (classmethods)", [
        "AssetToolsHelpers", "AssetRegistryHelpers", "EditorAssetLibrary",
        "MaterialEditingLibrary", "BlueprintEditorLibrary", "DataTableFunctionLibrary",
        "EditorUtilityLibrary", "EditorLoadingAndSavingUtils",
    ]),
    ("Common gameplay / math libraries", [
        "SystemLibrary", "GameplayStatics", "MathLibrary", "KismetRenderingLibrary",
        "KismetMaterialLibrary",
    ]),
    ("Actors / components / core types", [
        "Actor", "StaticMeshActor", "StaticMeshComponent", "SceneComponent",
        "PrimitiveComponent", "StaticMesh", "SkeletalMesh", "MaterialInterface",
        "MaterialInstanceConstant", "Material", "Texture2D", "TextureRenderTarget2D",
        "Blueprint", "DataAsset",
    ]),
    ("Lighting / sky / rendering", [
        "DirectionalLightComponent", "SkyLightComponent", "SkyAtmosphereComponent",
        "PostProcessVolume", "SphereReflectionCapture", "ReflectionCaptureComponent",
    ]),
    ("Landscape / foliage / PCG", [
        "Landscape", "LandscapeProxy", "InstancedFoliageActor",
        "FoliageType_InstancedStaticMesh", "PCGComponent", "PCGGraph",
    ]),
    ("Virtual textures (RVT)", [
        "RuntimeVirtualTexture", "RuntimeVirtualTextureComponent", "VirtualTextureBuilder",
    ]),
    ("Niagara / audio / animation", [
        "NiagaraSystem", "NiagaraComponent", "NiagaraFunctionLibrary",
        "AudioComponent", "SoundBase", "AnimSequence", "AnimMontage",
    ]),
    ("Sequencer / cinematics", [
        "LevelSequence", "MovieSceneSequenceExtensions", "CineCameraActor",
        "CineCameraComponent",
    ]),
    ("Misc utility", ["Paths", "EditorFilterLibrary", "Name", "SoftObjectPath"]),
]


def class_doc(name):
    cls = getattr(unreal, name, None)
    if cls is None:
        return None
    doc = (getattr(cls, "__doc__", None) or "").strip()
    if not doc:
        # Fall back to a dir() listing of public callables.
        members = [m for m in dir(cls) if not m.startswith("_")]
        doc = "Members:\n" + "\n".join("  " + m for m in members)
    return doc


def main():
    out_dir = os.path.join(unreal.Paths.project_plugins_dir(), "SpecialAgentPlugin", "docs")
    if not os.path.isdir(out_dir):
        os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "ue5_python_api_reference.md")

    ver = unreal.SystemLibrary.get_engine_version()
    lines = [
        "# UE5 Python API Reference (this build)",
        "",
        f"Engine: `{ver}`. Generated by `Content/Python/generate_api_reference.py`.",
        "",
        "Each section is the live `__doc__` of the class on THIS build (methods with",
        "signatures + brief descriptions). This is a curated subset — for any class use",
        "the `python/inspect_class`, `python/search_symbol`, `python/get_function_signature`",
        "tools, or `dir(unreal.<Class>)` / `help(unreal.<Class>.<method>)` in the console.",
        "",
        "See also `ue5_python_best_practices.md` (golden rules + subsystem map) and",
        "`deprecations.md` (deprecated -> modern API).",
        "",
        "---",
        "",
    ]
    missing = []
    for title, names in GROUPS:
        lines.append(f"# {title}")
        lines.append("")
        for name in names:
            doc = class_doc(name)
            lines.append(f"## unreal.{name}")
            lines.append("")
            if doc is None:
                lines.append("_(not available on this build)_")
                missing.append(name)
            else:
                lines.append("```text")
                lines.append(doc)
                lines.append("```")
            lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    unreal.log(f"SpecialAgent: wrote API reference -> {out_path}")
    if missing:
        unreal.log_warning("SpecialAgent: classes not on this build: " + ", ".join(missing))
    return out_path


main()
